MVC_Model2/src/java/com/wpsj/model/ProductBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wpsj.model;

import com.wpsj.da.ProductDataAccess;
import com.wpsj.entity.Product;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author HP
 */
public class ProductBean {
    public List<Product> getAllProduct() throws SQLException, ClassNotFoundException{
        return new ProductDataAccess().getProducts();
    }
}

MVC_Model2/src/java/com/wpsj/model/ProductFinderBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wpsj.model;

import com.wpsj.da.ProductDataAccess;
import com.wpsj.entity.Product;
import java.util.List;

/**
 *
 * @author HP
 */
public class ProductFinderBean {
    private String keyword;

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public List<Product> getProducts(){
        return new
            ProductDataAccess().getProductsByName(keyword);
    }
    
    
}

MVC_Model2/web/add.jsp
<%-- 
    Document   : AddForm
    Created on : Dec 11, 2019, 11:41:22 AM
    Author     : HP
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Add Product!</h1>
        <a href="search.jsp">Search</a>
        <a href="showAllPro.jsp">All Products</a>
        <form action="AddPost">
            Id: <input type="text" name="pro_id"><br/>
            Name: <input type="text" name="pro_name"><br/>
            Description: <input type="text" name="pro_desc"><br/>
            <input type="submit" value="Add">
        </form>
    </body>
</html>

MVC_Model2/web/login-error.jsp
<%-- 
    Document   : login-error
    Created on : Dec 11, 2019, 9:59:17 AM
    Author     : HP
--%>
<%@page import="bean.LoginBean" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <form action="login-error.jsp" method="post">
            <p style="color: red;margin: 50px auto;font-size: 18px;width: 300px">Sorry! username or password error</p>
            <%@include file="index.html" %>
        </form>
    </body>
</html>

MVC_Model2/web/login-success.jsp
<%-- 
    Document   : login-success
    Created on : Dec 11, 2019, 10:08:04 AM
    Author     : HP
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <style>
            .tittle{margin: 10px auto;font-size: 20px;width: 320px;font-weight: bold}
            .tittlep{margin-top: 50px}
        </style>
    </head>
    <body>
        <form action="login-success.jsp" method="post">
            <p class="tittle tittlep"> You are successfully logged in!</p>
            <p class="tittle">
            <jsp:useBean id="bean" class="bean.LoginBean" scope="request"/>
            <h3>Welcome to the new world <a style='color: rgb(37,232,151);margin:center'><%=bean.getName()%></a>
            <%@include file="index.html" %>

        </form>
    </body>
</html>

MVC_Model2/web/result.jsp
<%-- 
    Document   : result
    Created on : Dec 11, 2019, 10:31:04 AM
    Author     : HP
--%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>List Product</title>
    </head>
    <body>
        <h1>List Product!</h1>
        <a href="search.jsp">Search</a>
        <a href="showAllPro.jsp">All Products</a>
        <jsp:useBean class="com.wpsj.model.ProductFinderBean" id="finder" scope="request"/>
        
        <table>
            <tr>
                <td>Id</td>
                <td>Name</td>
                <td>Description</td>
                <td></td>
            </tr>
            <c:forEach items="${finder.products}" var="product">
                <tr>
                    <td><c:out value="${product.id}"/></td>
                    <td><c:out value="${product.name}"/></td>
                    <td><c:out value="${product.desc}"/></td>
                </tr>
                
            </c:forEach>
        </table>
    </body>
</html>

MVC_Model2/web/search.jsp
<%-- 
    Document   : search
    Created on : Dec 11, 2019, 10:31:16 AM
    Author     : HP
--%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<c:if test="${sessionScope.name==null}">
    <jsp:forward page="index.html"/>
</c:if>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Shopping!</title>
    </head>
    <body>
        <h1>Product List</h1>
        <form action="ProductFinder">
            <span style="color: red;">
                <c:out value="${param.msg}"/>
            </span>
            <input name="name"/><input type="submit"/>
            <a href="showAllPro.jsp">All Products</a><br>
        </form>
    </body>
</html>

MVC_Model2/web/showAllPro.jsp
<%-- 
    Document   : showAllPro
    Created on : Dec 12, 2019, 8:01:13 PM
    Author     : HP
--%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<c:if test="${sessionScope.name==null}">
    <jsp:forward page="index.html"/>
</c:if>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h4>Hi, ${sessionScope.name}</h4>
        <h1>All Product!</h1>
        <a href="search.jsp">Search</a><br>
        <a href="AddProduct">Create New</a>
        <jsp:useBean class="com.wpsj.model.ProductBean" id="finder" scope="request"/>
        <table>
            <tr>
                <td style="font-weight: bold">ID</td>
                <td style="font-weight: bold">Name</td>
                <td style="font-weight: bold">Description</td>
                <td style="font-weight: bold">Action</td>
            </tr>
            <c:forEach items="${finder.allProduct}" var="product">
                <tr>
                    <td><c:out value="${product.id}"/></td>
                    <td><c:out value="${product.name}"/></td>
                    <td><c:out value="${product.desc}"/></td>
                    <td><a  href="UpdateProduct?id=${product.id}">Edit</a>
                        <a href="DeleteProduct?id=${product.id}">Delete</a></td>
                </tr>
            </c:forEach>
        </table>
        <a href="LogoutServlet">Logout</a>
    </body>
</html>

MVC_Model2/web/update.jsp
<%-- 
    Document   : update
    Created on : Dec 12, 2019, 11:36:26 PM
    Author     : HP
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Edit Product!</h1>
        <a href="search.jsp">Search</a>
        <a href="showAllPro.jsp">All Products</a>
        <form action="UpdatePost" method="post">
            Id: <input type="text" name="pro_id"><br/>
            Name: <input type="text" name="pro_name"><br/>
            Description: <input type="text" name="pro_desc"><br/>
            <input type="submit" value="Update">
        </form>
    </body>
</html>